name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: './gradlew :FEND:H99PA288:jar'
    - name: Save jar file
      uses: actions/upload-artifact@v3
      with:
        name: H99PA288
        path: FEND/H99PA288/build/libs/H99PA288.jar